# Inferenzstatistik
## $p$-Wert und Kendall's $\tau_b$ interpretieren
```{r inf05, echo = FALSE, message = FALSE, results = "asis", warning=FALSE}
library(exams2forms)
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/inferenzstatistik/interpretation-taub-p/exams/interpretation-taub-p.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 15)
```

## $p$-Wert und Cohen's $U_3$ interpretieren
```{r inf06, echo = FALSE, message = FALSE, results = "asis", warning=FALSE}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/inferenzstatistik/interpretation-u3-p/exams/interpretation-u3-p.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 15)
```


## $p$-Wert und Cohen's $d$ interpretieren
```{r inf02, echo = FALSE, message = FALSE, results = "asis", warning=FALSE}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/inferenzstatistik/interpretation-cohen-d-p/exams/interpretation-cohen-d-p.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 15)
```

## Bayes Faktoren Abbildungen zuordnen
```{r inf01, echo = FALSE, message = FALSE, results = "asis", warning=FALSE}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/inferenzstatistik/bf-abbildung-zuordnen/exams/bf-abbildung-zuordnen.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 15)
```

## Bayes Faktor und Cohen's $d$ interpretieren
```{r inf03, echo = FALSE, message = FALSE, results = "asis", warning=FALSE}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/inferenzstatistik/interpretation-cohen-d-bf/exams/interpretation-cohen-d-bf.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 15)
```

## Bayes Faktor und Pearson's $r$ interpretieren
```{r inf04, echo = FALSE, message = FALSE, results = "asis", warning=FALSE}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/inferenzstatistik/interpretation-r-bf/exams/interpretation-r-bf.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 15)
```

## Inferenzstatistiken erkennen
```{r inf07, echo = FALSE, message = FALSE, results = "asis", warning=FALSE}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/inferenzstatistik/welche-koeffizienten-sind-inferenzstatistiken/exams/welche-koeffizienten-sind-inferenzstatistiken.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 15)
```

