# Messtheorie
## Zuordnungen als Homomorphismus identifizieren
```{r quiz1, echo = FALSE, message = FALSE, results = "asis", warning=FALSE}
library(exams2forms)
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/messtheorie/messung-als-homomorphismus/exams/messung-als-homomorphismus-geschlecht.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```

```{r quiz2, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/messtheorie/messung-als-homomorphismus/exams/messung-als-homomorphismus-grundschulempfehlung.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```

```{r quiz3, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/messtheorie/messung-als-homomorphismus/exams/messung-als-homomorphismus-klausurleistung.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```


## Skalenniveaus erkennen
```{r quiz4, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/messtheorie/skalenniveau-erkennen/exams/skalenniveau-erkennen.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```

## Inferenzniveau zuordnen
```{r quiz5, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/messtheorie/inferenzniveau-erkennen/exams/inferenzniveau-erkennen.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```

## Abhängige Variable identifizieren
```{r quiz6, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/messtheorie/av-identifizieren/exams/av-identifizieren.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```



## Abhängige, Unabhängige und Moderatorvariable in Abstract identifizieren
```{r quiz8, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/messtheorie/av-uv-mov-identifizieren-text/exams/av-uv-mov-identifizieren-text.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```


## Guetekriterien einer Messung erkennen
```{r quiz9, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/messtheorie/guetekriterien-einer-messung-erkennen/exams/guetekriterien-einer-messung-erkennen.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```


## Itempolaritaet zuordnen
```{r quiz10, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/messtheorie/itempolaritaet-erkennen/exams/itempolaritaet-erkennen.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```


## Bezugsnormen in Aussagen erkennen
```{r quiz11, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/messtheorie/bezugsnormen-erkennen/exams/bezugsnormen-erkennen.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```

