# Methodologie
## Gütekriterien wissenschaftlicher Erkenntnisse erkennen
```{r quiz, echo = FALSE, message = FALSE, results = "asis", warning=FALSE}
library(exams2forms)
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/methodologie/guetekriterium-wissenschaftlicher-erkenntnis-erkennen/exams/guetekriterium-wissenschaftlicher-erkenntnis-erkennen.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```


## Erkenntnisinteresse erkennen
```{r quiz2, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/methodologie/erkenntnisinteresse/exams/Deskriptive_Explorative_Explanative_Studien_r.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```


## Designs unterscheiden
```{r quiz3, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/methodologie/experimentelles-design/exams/Exp_Quasiexp_Nichtexp_Studien_r.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```


## Aussagen zu Gütekriterien
```{r quiz4, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/methodologie/guetekriterien-gemischt-mc/exams/guetekriterien-gemischt-mc.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```


## Vergleich der methodischen Strenge
```{r quiz5, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/methodologie/methodische-strenge-vergleichen/exams/methodische-strenge-vergleichen.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```


## Steigerung der externen Validitaet
```{r quiz6, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/methodologie/steigerung-externe-validitaet/exams/steigerung-externe-validitaet.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```


## Steigerung der internen Validitaet
```{r quiz7, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/methodologie/steigerung-interne-validitaet/exams/steigerung-interne-validitaet.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```


## Verschiedenen Designs interne Validitaet zuordnen
```{r quiz8, echo = FALSE, message = FALSE, results = "asis"}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/methodologie/dem-design-interne-validitaet-zuordnen/exams/dem-design-interne-validitaet-zuordnen.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 20)
```
