# Qualitative Methoden
## Induktion, Deduktion, Abduktion
```{r qual01, echo = FALSE, message = FALSE, results = "asis", warning=FALSE}
library(exams2forms)
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/qualitative-methoden/Induktion_Deduktion_Abduktion.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 15)
```

## Typisch Qualitative/Quantitative Methodologie
```{r qual02, echo = FALSE, message = FALSE, results = "asis", warning=FALSE}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/qualitative-methoden/TypischQuali_TypischQuanti.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 15)
```

## Deduktive/Induktive Inhaltsanalyse
```{r inf03, echo = FALSE, message = FALSE, results = "asis", warning=FALSE}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/qualitative-methoden/Ded_Ind_IndDed_Inhaltsanalyse.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 15)
```

## Passung Forschungsfrage & Datenerhebungsmethode
```{r inf04, echo = FALSE, message = FALSE, results = "asis", warning=FALSE}
download.file("https://raw.githubusercontent.com/sammerk/aufgaben/refs/heads/master/qualitative-methoden/FF_vs_Datenerhebung.Rmd",
              "tempfile.Rmd")
exams2forms("tempfile.Rmd", n = 15)
```
